# Generated by Django 2.0.5 on 2018-05-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180518_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTinymce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(blank=True, null=True, verbose_name='测试')),
            ],
        ),
    ]
