# Generated by Django 2.0.5 on 2018-05-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_testtinymce'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testtinymce',
            options={'verbose_name': '测试', 'verbose_name_plural': '测试'},
        ),
        migrations.RemoveField(
            model_name='testtinymce',
            name='txt',
        ),
        migrations.AddField(
            model_name='testtinymce',
            name='content',
            field=models.TextField(default='', verbose_name='文本'),
        ),
        migrations.AddField(
            model_name='testtinymce',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='标题'),
        ),
        migrations.AlterModelTable(
            name='testtinymce',
            table='test_tinymce',
        ),
    ]
