# Generated by Django 2.0.5 on 2018-05-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180518_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testtinymce',
            options={},
        ),
        migrations.RemoveField(
            model_name='testtinymce',
            name='content',
        ),
        migrations.RemoveField(
            model_name='testtinymce',
            name='title',
        ),
        migrations.AddField(
            model_name='testtinymce',
            name='txtt',
            field=models.TextField(default=''),
        ),
        migrations.AlterModelTable(
            name='testtinymce',
            table=None,
        ),
    ]
