# Generated by Django 2.0.5 on 2018-05-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180518_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTinymce',
        ),
    ]
